import type { Metadata } from "next";
import "./globals.css";
import { CartProvider } from "./hooks/useCart";
import { cookies } from "next/headers";
import { getCart } from "./lib/shopify";
import { ProductProvider } from "./hooks/useProduct";
import NavBar from "./components/NavBar/page";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const cartId = cookieStore.get("cartId")?.value;
  const cart = getCart(cartId);

  return (
    <html lang="en">
      <body>
        <CartProvider cartPromise={cart}>
          <ProductProvider>
            <NavBar />
            {children}
          </ProductProvider>
        </CartProvider>
      </body>
    </html>
  );
}
